### ISSUE TITLE
Tradition policy does not work

### ISSUE THREAD

**Issue by ajustsomebody** [k4zoo/Civ5ExpansionMod#31] opened 2021-05-11 10:17 UTC

**Comment by cbirv** [comment] 2021-05-13 23:19
Tradition Opener does not provide +3 Culture in capital, I can't verify if it's reducing culture costs. It does unlock Hanging Gardens.

Legalism looks like it works as intended.

One of Monarchy or Aristocracy isn't providing their Happiness bonus - or it isn't showing up on the stats drilldown or stats overview. 

Aristrocracy's wonder production bonus looks like it works.

Landed Elite's food bonus works, can't verify the growth.

**Comment by ajustsomebody** [comment] 2021-05-14 09:55
> Tradition Opener does not provide +3 Culture in capital, I can't verify if it's reducing culture costs. It does unlock Hanging Gardens.
> 
> Legalism looks like it works as intended.
> 
> One of Monarchy or Aristocracy isn't providing their Happiness bonus - or it isn't showing up on the stats drilldown or stats overview. 
> 
> Aristrocracy's wonder production bonus looks like it works.
> 
> Landed Elite's food bonus works, can't verify the growth. 

so that means it will be fixed?

**Comment by cbirv** [comment] 2021-05-16 13:10
No idea. I had the same issue so I wanted to add on to your post so all issues with the policy tree are visible in one place

**Comment by cbirv** [comment] 2021-05-25 05:20
This was a main game bug that was fixed in this commit.
https://github.com/yairm210/Unciv/commit/7e7f72ed2f19517d0c0168dd4c14bef22c7c6c4d#diff-2a2d3eccce78e24ee31b90b57400cb88d2c9140626a393fd5cc9e62e3dcdb1db

It's a pretty simple fix: put "[ ]" around "in capital" for Tradition in Policies.json

**Comment by ajustsomebody** [comment] 2021-06-06 14:59
> This was a main game bug that was fixed in this commit.
> https://github.com/yairm210/Unciv/commit/7e7f72ed2f19517d0c0168dd4c14bef22c7c6c4d#diff-2a2d3eccce78e24ee31b90b57400cb88d2c9140626a393fd5cc9e62e3dcdb1db
> 
> It's a pretty simple fix: put "[ ]" around "in capital" for Tradition in Policies.json

yeah but it still persists in this mod

**Closed as completed** 2021-08-20 14:51 UTC
